name: jime_compendium
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  lottie: ^3.1.0
  widget_driver: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  widget_driver_generator: ^1.0.3
  widget_driver_test: ^1.0.4
  mocktail: ^0.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_logo.png
    - assets/images/onboarding_1.jpg
    - assets/images/onboarding_2.jpg
    - assets/images/onboarding_3.jpg
    - assets/images/onboarding_4.jpg
    - assets/lottie/castle.json
    - assets/lottie/warning.json
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Raleway-Thin.ttf
          weight: 100
